# Generated by Django 5.2.5 on 2025-08-19 23:48

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0025_alter_pet_foto_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='pet_images/secondary/'),
        ),
    ]
