# Generated by Django 5.2.5 on 2025-08-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0026_alter_petimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/'),
        ),
        migrations.AlterField(
            model_name='petimage',
            name='image',
            field=models.ImageField(upload_to='pet_images/secondary/'),
        ),
    ]
