# Generated by Django 5.2.5 on 2025-08-20 02:09

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0027_alter_pet_foto_principal_alter_petimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='pet_images/'),
        ),
        migrations.AlterField(
            model_name='petimage',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='pet_images/secondary/'),
        ),
    ]
